config/routes.rb
Rails.application.routes.draw do
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["Dog", "Cat", "Turtle", "Lizard", "Bird"]
  validates :name, :species, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show 
  end

  def new 
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
  end

  def update 
    if @pet.update(pet_params)
      redirect_to pet_path(@pet.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private 

  def set_pet 
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<%= form_with model: @pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<h1>Checkout these cute pets 🐶😺🐢</h1>

<% @pets.each do |pet| %>
  <p><%= link_to pet.name, pet_path(pet) %></p>
  <p>Species: <%= pet.species %></p>
  <p>Lives in <%= pet.address %></p>
<% end %>

<%= link_to "Add a lost pet", new_pet_path %>

app/views/pets/new.html.erb
<%= form_with model: @pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, collection: Pet::SPECIES %>
  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h3><%= @pet.address %></h3>
<%= link_to "I found this pet", pet_path(@pet), data: {turbo_method: :delete, turbo_confirm: "You found this pet?"} %>